import { Expense } from "@/lib/types/expense";

export const DEMO_EXPENSES: Expense[] = [
  {
    id: "exp-demo-001",
    user_id: "demo-user-id",
    expense_name: "Market Data",
    expense_date: "2026-05-02",
    category: "Market Data",
    description: "OPRA level 2 real-time options data feed",
    original_amount: 250.0,
    billed_currency: "USD",
    vendor: "Interactive Brokers",
    account: "Master Trading",
    payment_method: "Credit Card",
    expense_type: "OPERATING",
    business_purpose: "Market data execution feed",
    business_use_percent: 100,
    receipt_number: "REC-2026-0502",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-01",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Essential OPRA data subscription.",
    receipt_url: null,
    created_at: "2026-05-02T08:00:00Z",
    updated_at: "2026-05-02T08:00:00Z",
  },
  {
    id: "exp-demo-002",
    user_id: "demo-user-id",
    expense_name: "Platform Fee",
    expense_date: "2026-05-05",
    category: "Trading Platform",
    description: "Trader workstation platform software fee",
    original_amount: 180.0,
    billed_currency: "USD",
    vendor: "Interactive Brokers",
    account: "Master Trading",
    payment_method: "Account Debit",
    expense_type: "OPERATING",
    business_purpose: "Direct market execution terminal",
    business_use_percent: 100,
    receipt_number: "REC-2026-0505",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-02",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "TWS pro terminal software fee.",
    receipt_url: null,
    created_at: "2026-05-05T08:00:00Z",
    updated_at: "2026-05-05T08:00:00Z",
  },
  {
    id: "exp-demo-003",
    user_id: "demo-user-id",
    expense_name: "News Service",
    expense_date: "2026-05-08",
    category: "Research & News",
    description: "Real-time economic catalyst audio news feed",
    original_amount: 120.0,
    billed_currency: "USD",
    vendor: "TradingView",
    account: "Options Growth",
    payment_method: "Credit Card",
    expense_type: "OPERATING",
    business_purpose: "Real-time news tracking",
    business_use_percent: 100,
    receipt_number: "REC-2026-0508",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-03",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Audio squawk news service.",
    receipt_url: null,
    created_at: "2026-05-08T08:00:00Z",
    updated_at: "2026-05-08T08:00:00Z",
  },
  {
    id: "exp-demo-004",
    user_id: "demo-user-id",
    expense_name: "Trading Course",
    expense_date: "2026-05-12",
    category: "Education",
    description: "Advanced options risk management training course",
    original_amount: 499.0,
    billed_currency: "USD",
    vendor: "TradingView",
    account: "Master Trading",
    payment_method: "Wire Transfer",
    expense_type: "DEVELOPMENT",
    business_purpose: "Options education course",
    business_use_percent: 100,
    receipt_number: "REC-2026-0512",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: false,
    frequency: null,
    start_date: null,
    recurring_group_id: null,
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "One-time education masterclass.",
    receipt_url: null,
    created_at: "2026-05-12T08:00:00Z",
    updated_at: "2026-05-12T08:00:00Z",
  },
  {
    id: "exp-demo-005",
    user_id: "demo-user-id",
    expense_name: "VPS Hosting",
    expense_date: "2026-05-15",
    category: "VPS / Hosting",
    description: "Dedicated low-latency server hosting",
    original_amount: 150.0,
    billed_currency: "USD",
    vendor: "Interactive Brokers",
    account: "Master Trading",
    payment_method: "Credit Card",
    expense_type: "OPERATING",
    business_purpose: "Low-latency server hosting",
    business_use_percent: 100,
    receipt_number: "REC-2026-0515",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-04",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "High reliability datacenter VPS.",
    receipt_url: null,
    created_at: "2026-05-15T08:00:00Z",
    updated_at: "2026-05-15T08:00:00Z",
  },
  {
    id: "exp-demo-006",
    user_id: "demo-user-id",
    expense_name: "Analytics Tool",
    expense_date: "2026-05-18",
    category: "Software & Tools",
    description: "Premium charting and analytics suite subscription",
    original_amount: 99.0,
    billed_currency: "USD",
    vendor: "TradingView",
    account: "Master Trading",
    payment_method: "Credit Card",
    expense_type: "OPERATING",
    business_purpose: "Technical chart analysis suite",
    business_use_percent: 100,
    receipt_number: "REC-2026-0518",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-05",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Charting and analytics suite.",
    receipt_url: null,
    created_at: "2026-05-18T08:00:00Z",
    updated_at: "2026-05-18T08:00:00Z",
  },
  {
    id: "exp-demo-007",
    user_id: "demo-user-id",
    expense_name: "Funded Eval",
    expense_date: "2026-05-22",
    category: "Funded Account Fees",
    description: "Capital allocation challenge setup fee",
    original_amount: 220.0,
    billed_currency: "USD",
    vendor: "Interactive Brokers",
    account: "Options Growth",
    payment_method: "Credit Card",
    expense_type: "OPERATING",
    business_purpose: "Account evaluation challenge",
    business_use_percent: 100,
    receipt_number: "REC-2026-0522",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: false,
    frequency: null,
    start_date: null,
    recurring_group_id: null,
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Evaluation challenge fee.",
    receipt_url: null,
    created_at: "2026-05-22T08:00:00Z",
    updated_at: "2026-05-22T08:00:00Z",
  },
  {
    id: "exp-demo-008",
    user_id: "demo-user-id",
    expense_name: "Internet",
    expense_date: "2026-05-25",
    category: "Office & Internet",
    description: "Symmetrical trading office fiber line",
    original_amount: 135.0,
    billed_currency: "USD",
    vendor: "TradingView",
    account: "Master Trading",
    payment_method: "Direct Debit",
    expense_type: "UTILITIES",
    business_purpose: "Office primary internet line",
    business_use_percent: 85,
    receipt_number: "REC-2026-0525",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: true,
    frequency: "Monthly",
    start_date: "2026-01-01",
    recurring_group_id: "rec-group-06",
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 85,
    notes: "Primary business network line.",
    receipt_url: null,
    created_at: "2026-05-25T08:00:00Z",
    updated_at: "2026-05-25T08:00:00Z",
  },
  {
    id: "exp-demo-009",
    user_id: "demo-user-id",
    expense_name: "Tax Consulting",
    expense_date: "2026-05-27",
    category: "Professional Services",
    description: "Quarterly section 475(f) tax advisory session",
    original_amount: 350.0,
    billed_currency: "USD",
    vendor: "Interactive Brokers",
    account: "Master Trading",
    payment_method: "Bank Transfer",
    expense_type: "PROFESSIONAL",
    business_purpose: "Trader status tax advisory",
    business_use_percent: 100,
    receipt_number: "REC-2026-0527",
    tax_type: "ORDINARY_BUSINESS",
    tax_amount: 0,
    is_recurring: false,
    frequency: null,
    start_date: null,
    recurring_group_id: null,
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Quarterly CPA tax planning.",
    receipt_url: null,
    created_at: "2026-05-27T08:00:00Z",
    updated_at: "2026-05-27T08:00:00Z",
  },
  {
    id: "exp-demo-010",
    user_id: "demo-user-id",
    expense_name: "Trading Hardware",
    expense_date: "2026-05-29",
    category: "Hardware & Gear",
    description: "Ergonomic triple monitor mounting arm",
    original_amount: 179.0,
    billed_currency: "USD",
    vendor: "TradingView",
    account: "Master Trading",
    payment_method: "Credit Card",
    expense_type: "CAPITAL",
    business_purpose: "Trading station desk hardware",
    business_use_percent: 100,
    receipt_number: "REC-2026-0529",
    tax_type: "SECTION_179",
    tax_amount: 0,
    is_recurring: false,
    frequency: null,
    start_date: null,
    recurring_group_id: null,
    is_template: false,
    is_generated: false,
    is_active: true,
    is_deleted: false,
    is_tax_deductible: true,
    deductible_percent: 100,
    notes: "Desk monitor arm setup.",
    receipt_url: null,
    created_at: "2026-05-29T08:00:00Z",
    updated_at: "2026-05-29T08:00:00Z",
  },
];
