/**
 * ============================================================================
 * ELITEX TRADING OS
 * Build Expense Report Data
 * ============================================================================
 *
 * Converts application expense data into a canonical ExpenseReportData object.
 *
 * Responsibilities
 * ----------------------------------------------------------------------------
 * • Validate input
 * • Build report metadata
 * • Build executive summary
 * • Build category summary
 * • Build original currency totals
 * • Build printable expense rows
 * • Build report information
 * • Build disclaimer
 *
 * This file performs all business logic required by the Expense Report.
 *
 * It MUST NOT contain any PDF rendering logic.
 *
 * ============================================================================
 */

import {
  BuildExpenseReportDataInput,
  ExpenseReportData,
  ExpenseReportMetadata,
} from "./types";

export function buildExpenseReportData(
  input: BuildExpenseReportDataInput
): ExpenseReportData {

  validateInput(input);

  const metadata = buildMetadata(input);

  throw new Error(
    "buildExpenseReportData() not implemented."
  );

}

/* ============================================================================
   Validation
   ============================================================================ */

function validateInput(
  input: BuildExpenseReportDataInput
): void {

  if (!Array.isArray(input.expenses)) {
    throw new Error("Expenses must be an array.");
  }

  if (!input.reportingCurrency) {
    throw new Error("Reporting currency is required.");
  }

  if (!input.reportingPeriod) {
    throw new Error("Reporting period is required.");
  }

  if (!input.generatedBy) {
    throw new Error("Generated by is required.");
  }

  if (!input.reportVersion) {
    throw new Error("Report version is required.");
  }

}

/* ============================================================================
   Metadata
   ============================================================================ */

function buildMetadata(
  input: BuildExpenseReportDataInput
): ExpenseReportMetadata {

  return {
    reportName: "Business Expense Report",

    generatedAt: new Date(),

    reportingCurrency: input.reportingCurrency,

    reportingPeriod: input.reportingPeriod,
  };

}