/**
 * ============================================================================
 * ELITEX TRADING OS
 * Build Expense Report Data
 * ============================================================================
 *
 * Converts canonical ReportingExpense data into a printable
 * ExpenseReportData object.
 *
 * Responsibilities
 * ----------------------------------------------------------------------------
 * • Validate input
 * • Orchestrate report builders
 * • Return canonical report data
 *
 * Performs NO PDF rendering.
 *
 * ============================================================================
 */

import { buildCategorySummary } from "./builders/categorySummary";
import { buildVendorSummary } from "./builders/vendorSummary";
import { buildDisclaimer } from "./builders/disclaimer";
import { buildLedger } from "./builders/ledger";
import { buildMetadata } from "./builders/metadata";
import { buildReportInformation } from "./builders/reportInformation";
import { buildSummary } from "./builders/summary";
import { buildOriginalCurrencyTotals } from "./builders/originalCurrencyTotals";

import {
  BuildExpenseReportDataInput,
  ExpenseReportData,
} from "./types";

/* ============================================================================
   Build Expense Report Data
   ============================================================================ */

export function buildExpenseReportData(
  input: BuildExpenseReportDataInput
): ExpenseReportData {

  validateInput(input);

  return {

    metadata:
      buildMetadata(input),

    options:
      input.options,

    summary:
      buildSummary(
        input.expenses
      ),

categorySummary:
  buildCategorySummary(
    input.expenses
  ),

vendorSummary:
  buildVendorSummary(
    input.expenses
  ),

originalCurrencyTotals:
  buildOriginalCurrencyTotals(
    input.expenses
  ),

rows:
  buildLedger(
    input.expenses,
    input.reportingCurrency,
    input.options
  ),

    reportInformation:
      buildReportInformation(
        input.expenses,
        input
      ),

    disclaimer:
      buildDisclaimer(),
  };

}

/* ============================================================================
   Validation
   ============================================================================ */

function validateInput(
  input: BuildExpenseReportDataInput
): void {

  if (!Array.isArray(input.expenses)) {
    throw new Error(
      "Expenses must be an array."
    );
  }

  if (!input.reportingCurrency) {
    throw new Error(
      "Reporting currency is required."
    );
  }

  if (!input.reportingPeriod) {
    throw new Error(
      "Reporting period is required."
    );
  }

  if (!input.generatedBy) {
    throw new Error(
      "Generated by is required."
    );
  }

  if (!input.reportVersion) {
    throw new Error(
      "Report version is required."
    );
  }

}